POST HTTP://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthbGxlSyIsImlkIjoiNjc3Zjk2MzgyNTEyYzllZTdlNTljMjg0IiwiaWF0IjoxNzM2NDk2NDkxfQ.MnYUAF24LQEDiG1IrBUp3Dv2N3_SHTXZIkMwANhRr50

{
    "title": "Otsikko",
    "author": "Kalle",
    "url": "www.blogiteksti.esim",
    "likes": 5,
    "userId": "677f96382512c9ee7e59c284"
}
