POST HTTP://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Otsikko",
    "author": "Kalle",
    "url": "www.blogiteksti.esim",
    "likes": 5,
    "userId": "677f96382512c9ee7e59c284"
}
